#!/usr/bin/env bash
# =============================================================================
# UnBot Delivery — Mosquitto Broker Setup (Ubuntu 22.04 LTS)
# Ticket #1 / Task A
#
# Scope: Install Mosquitto, disable anonymous access, create two M2M
#        credentials (gateway + esp32). No TLS in this iteration.
#
# Usage:
#   chmod +x setup_mosquitto.sh
#   sudo ./setup_mosquitto.sh
#
# Credentials are written to /etc/mosquitto/passwd (hashed by mosquitto_passwd).
# Override the defaults below via environment variables before running:
#
#   GATEWAY_PASS=s3cur3 ESP32_PASS=s3cur3 sudo -E ./setup_mosquitto.sh
# =============================================================================

set -euo pipefail

# ── Configurable defaults (override via env) ──────────────────────────────────
GATEWAY_USER="${GATEWAY_USER:-gateway}"
GATEWAY_PASS="${GATEWAY_PASS:-changeme_gateway}"
ESP32_USER="${ESP32_USER:-esp32}"
ESP32_PASS="${ESP32_PASS:-changeme_esp32}"

MQTT_PORT="${MQTT_PORT:-1883}"
PASSWD_FILE="/etc/mosquitto/passwd"
CONF_FILE="/etc/mosquitto/conf.d/unbot.conf"

# ── Sanity check ──────────────────────────────────────────────────────────────
if [[ "$EUID" -ne 0 ]]; then
  echo "[ERROR] Run as root: sudo ./setup_mosquitto.sh" >&2
  exit 1
fi

echo "[1/5] Installing Mosquitto..."
apt-get update -qq
apt-get install -y mosquitto mosquitto-clients

# ── Stop broker before touching config ───────────────────────────────────────
systemctl stop mosquitto || true

# ── Create password file with both M2M users ─────────────────────────────────
echo "[2/5] Creating M2M credentials..."

# -c creates/overwrites the file; first user must use -c, subsequent use -b
mosquitto_passwd -c -b "$PASSWD_FILE" "$GATEWAY_USER" "$GATEWAY_PASS"
mosquitto_passwd    -b "$PASSWD_FILE" "$ESP32_USER"   "$ESP32_PASS"

chmod 640 "$PASSWD_FILE"
chown mosquitto:mosquitto "$PASSWD_FILE"

echo "      Users written: $GATEWAY_USER, $ESP32_USER"

# ── Write broker config ───────────────────────────────────────────────────────
echo "[3/5] Writing broker config to $CONF_FILE..."

cat > "$CONF_FILE" <<EOF
# UnBot Delivery — Mosquitto listener config
# Generated by setup_mosquitto.sh — do not edit manually.

listener ${MQTT_PORT}

# Enforce M2M authentication — no anonymous clients permitted.
allow_anonymous false
password_file   ${PASSWD_FILE}

# Connection hygiene
max_keepalive          60
persistent_client_expiration 1h

# Logging (systemd-journald captures stdout)
log_dest   stdout
log_type   error
log_type   warning
log_type   subscribe
log_type   unsubscribe
EOF

chown mosquitto:mosquitto "$CONF_FILE"

# ── Enable and start ──────────────────────────────────────────────────────────
echo "[4/5] Enabling and starting Mosquitto..."
systemctl enable mosquitto
systemctl start  mosquitto

# Brief settle time before the smoke test
sleep 2

# ── Smoke test: gateway credential round-trip ─────────────────────────────────
echo "[5/5] Running smoke test (publish → subscribe with gateway credentials)..."

# Subscribe in the background, capture one message, then kill the subscriber.
RESULT=$(mosquitto_sub \
  -h 127.0.0.1 -p "$MQTT_PORT" \
  -u "$GATEWAY_USER" -P "$GATEWAY_PASS" \
  -t "unbot/setup/test" -C 1 --quiet &
SUB_PID=$!
sleep 1
mosquitto_pub \
  -h 127.0.0.1 -p "$MQTT_PORT" \
  -u "$GATEWAY_USER" -P "$GATEWAY_PASS" \
  -t "unbot/setup/test" -m "ok"
wait $SUB_PID 2>/dev/null || true
)

if [[ "$RESULT" == "ok" ]]; then
  echo ""
  echo "✅  Mosquitto is running on port ${MQTT_PORT} with M2M auth enforced."
  echo "    Gateway user : $GATEWAY_USER"
  echo "    ESP32 user   : $ESP32_USER"
  echo ""
  echo "⚠️  Reminder: rotate the default passwords before production use."
else
  echo "[ERROR] Smoke test failed — check 'journalctl -u mosquitto -n 50'" >&2
  exit 1
fi
